version: '3.8'

services:
    astronacci-api:
        container_name: astronacci-api
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
            - ./storage:/var/www/html/storage
        environment:
            - APP_NAME=Astronacci
            - APP_ENV=production
            - APP_DEBUG=false
            - APP_KEY=base64:kecPBbmgQ2OiUXk1kbKgCkFcBCR0kwtaNAEwVhtvD+8=
            - APP_URL=https://astronacci.richh.my.id
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=astronacci
            - DB_USERNAME=root
            - DB_PASSWORD=root
            - CACHE_STORE=database
            - SESSION_DRIVER=database
            - QUEUE_CONNECTION=database
            - MAIL_MAILER=smtp
            - MAIL_HOST=smtp.mailtrap.io
            - MAIL_PORT=2525
            - MAIL_USERNAME=your_mailtrap_username
            - MAIL_PASSWORD=your_mailtrap_password
            - MAIL_ENCRYPTION=tls
            - MAIL_FROM_ADDRESS=noreply@astronacci.com
            - MAIL_FROM_NAME=Astronacci
            - TZ=Asia/Jakarta
        restart: always
        ports:
            - "9000:9000"
        depends_on:
            - mysql
        networks:
            - laravel

    mysql:
        image: mysql:8.0
        container_name: mysql-astronacci
        restart: always
        environment:
            - MYSQL_DATABASE=astronacci
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - laravel

volumes:
    mysql-data:

networks:
    laravel:
        driver: bridge
