version: '3.8'

services:
    astronacci-api:
        container_name: astronacci-api
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
            - ./storage:/var/www/html/storage
        environment:
            - APP_NAME=Laravel
            - APP_ENV=production
            - APP_DEBUG=false
            - APP_KEY=base64:kecPBbmgQ2OiUXk1kbKgCkFcBCR0kwtaNAEwVhtvD+8=
            - APP_URL=http://localhost:8000
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=astronacci
            - DB_USERNAME=root
            - DB_PASSWORD=root
            - CACHE_STORE=database
            - SESSION_DRIVER=database
            - QUEUE_CONNECTION=database
            - MAIL_MAILER=smtp
            - MAIL_HOST=smtp.mailtrap.io
            - MAIL_PORT=2525
            - MAIL_USERNAME=your_mailtrap_username
            - MAIL_PASSWORD=your_mailtrap_password
            - MAIL_ENCRYPTION=tls
            - MAIL_FROM_ADDRESS=noreply@example.com
            - MAIL_FROM_NAME=Laravel
            - ONESIGNAL_REST_API_URL=https://api.onesignal.com
            - ONESIGNAL_APP_ID=ed858127-58a2-44c2-9936-f89290ee83a6
            - ONESIGNAL_REST_API_KEY=os_v2_app_5wcycj2yujcmfgjw7cjjb3uduzxcvnymwmqeqdnhq636722hds2akqdhtkd6s5smltrmvib6abma2cd46eslolunkaqtxrqcgnylc6q
            - TZ=Asia/Jakarta
        restart: always
        expose:
            - 9000
        depends_on:
            - mysql
        networks:
            - laravel

    webserver:
        image: nginx:alpine
        container_name: webserver-astronacci
        restart: always
        volumes:
            - .:/var/www/html
            - ./custom_nginx.conf:/etc/nginx/nginx.conf
            - ./nginx_services.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8000:80"
        depends_on:
            - astronacci-api
        networks:
            - laravel

    mysql:
        image: mysql:8.0
        container_name: mysql-astronacci
        restart: always
        environment:
            - MYSQL_DATABASE=astronacci
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - laravel

volumes:
    mysql-data:

networks:
    laravel:
        driver: bridge
